version: "3.7"
services:
    bot:
        image: ghcr.io/yoki-labs/bots/tuxedo/bot:latest
        container_name: TUXEDO_BOT
        restart: unless-stopped
        env_file:
            - ../../stack.env

