version: "3.7"
services:
    db:
        image: postgres
        restart: unless-stopped
        container_name: YOKI_DB
        environment:
            POSTGRES_DB: yoki
            POSTGRES_USER: yoki_user
            POSTGRES_PASSWORD: yoki_pass
        volumes:
            - yoki-postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - ./.env

volumes:
    yoki-postgres-data:
