version: "3.7"
services:
    bot:
        image: ghcr.io/yoki-labs/bots/yoki/bot:latest
        container_name: YOKI_BOT
        restart: unless-stopped
        network_mode: "host"
        env_file:
            - ./.env.prod
