version: "3.7"
services:
    bot:
        build:
            context: ../../
            dockerfile: ./docker/bot/Dockerfile
        container_name: YOKI_BOT
        restart: unless-stopped
        env_file:
            - ../../.env
        networks:
            - main-network

networks:
    main-network:
        driver: bridge
