version: "3.7"
services:
    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: yoki
            POSTGRES_USER: yoki_user
            POSTGRES_PASSWORD: yoki_pass

volumes:
  yoki-postgres-data: