version: "3.7"
services:
    bot:
        build:
            context: ../../
            dockerfile: ./bot/Dockerfile
        container_name: YOKI_BOT
        restart: unless-stopped
        depends_on:
            - cache
        env_file:
            - ../../

networks:
    main-network:
        driver: bridge