version: "3.7"
services:
    bot:
        image: docker.pkg.github.com/yoki-labs/yoki/bot
        container_name: YOKI_BOT
        restart: unless-stopped
        env_file:
            - ../../.env
        networks:
            - main-network
  
networks:
    main-network:
        driver: bridge