version: "3.7"
services:
    bot:
        image: ghcr.io/yoki-labs/yoki/bot:latest
        container_name: TUXEDO_BOT
        restart: unless-stopped
        networks:
            - main-network
    cache:
        image: redis/redis-stack-server:latest
        container_name: TUXEDO_CACHE
        restart: unless-stopped
        networks:
            - main-network
        ports:
            - "6379:6379"

networks:
    main-network:
        driver: bridge
