version: "3.7"
services:
  bot:
    image: ghcr.io/yoki-labs/yoki/bot:latest
    container_name: YOKI_BOT
    restart: unless-stopped
    networks:
      - main-network
  nsfw:
    image: ghcr.io/yoki-labs/yoki/nsfw:latest
    container_name: YOKI_NSFW_DETECTION
    restart: unless-stopped
    networks:
      - main-network
    ports:
      - "4433:4433"
  cache:
    image: redis/redis-stack-server:latest
    container_name: YOKI_CACHE
    restart: unless-stopped
    networks:
      - main-network
    ports:
      - "6379:6379"

networks:
  main-network:
    driver: bridge
