name: CI workflows
on: [push, pull_request]

jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Set up Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm -r install

      - name: Run linter
        run: pnpm lint

      - name: Build Yoki Prisma
        run: cd yoki/bot && pnpm generate

      - name: Build Yoki
        run: pnpm build:yoki

      - name: Build Tuxedo Prisma
        run: cd tuxedo/bot && pnpm generate

      - name: Build Tuxedo
        run: pnpm build:tuxedo
