name: CI workflows
on: [push, pull_request]

jobs:
    quality:
        name: Quality Check
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                service-name: [yoki, tuxedo]
        steps:
            - name: Clone repo
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 7.28.0

            - name: Set up Node v16
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Generate Prisma TypeScript
              run: cd ${{ matrix.service-name }}/bot && pnpx prisma generate

            - name: Run linter
              run: pnpm lint

            - name: Run TypeScript Compiler
              run: pnpm build
