name: CI workflows
on: [push, pull_request]

jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.28.0

      - name: Set up Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm -r install

      - name: Run linter
        run: pnpm lint

      - name: Build Yoki Prisma
        run: cd yoki/bot && pnpm generate

      - name: Build Yoki
        run: pnpm build:yoki

      - name: Build Tuxedo Prisma
        run: cd tuxedo/bot && pnpm generate

      - name: Build Tuxedo
        run: pnpm build:tuxedo
