name: Deploy to Production
on:
    push:
        branches:
            - main
jobs:
    docker:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service-name: [bot]
        steps:
            - uses: actions/checkout@v2
            - name: Build
              uses: jerray/publish-docker-action@v1.0.5
              with:
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: ${{ github.repository }}/${{ matrix.service-name }}
                  file: docker/${{ matrix.service-name }}/Dockerfile
    deploy:
        name: Deploy to Production
        needs: [docker]
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DO_HOST }}
                  username: nico
                  key: ${{ secrets.DO_KEY }}
                  port: 22005
                  script: |
                      cd yoki
                      cd docker/compose && docker-compose pull
                      cd ../../
                      ./run-prod.sh
