name: Deploy to Production
on:
    push:
        branches:
            - main
        paths:
            - "services/**"
            - "docker/**"
jobs:
    docker:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service-name: [bot]
        steps:
            - uses: actions/checkout@v2
            - name: Build
              uses: jerray/publish-docker-action@v1.0.5
              with:
                  username: ${{ secrets.DO_IMAGE_REGISTRY_KEY }}
                  password: ${{ secrets.DO_IMAGE_REGISTRY_KEY }}
                  registry: registry.digitalocean.com/yoki-labs
                  repository: ${{ github.repository }}/${{ matrix.service-name }}
                  file: docker/${{ matrix.service-name }}/Dockerfile
