name: Deploy to Production
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "services/**"
            - "!services/landing/**"
            - "!services/dashboard/**"
            - "docker/**"
jobs:
    docker:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service-name: [bot, nsfw]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Verify Changed files
              uses: dorny/paths-filter@v2
              id: verify-changed-files
              with:
                  filters: |
                      service:
                        - 'services/${{ matrix.service-name }}/src/**'
                        - 'docker/${{ matrix.service-name }}/**'

            - name: Set up QEMU
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/setup-buildx-action@v2

            - name: Login to GCR
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}/${{ matrix.service-name }}:latest
                  file: docker/${{ matrix.service-name }}/Dockerfile
    deploy:
        name: Deploy to Production
        needs: [docker]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

            - name: Verify Changed files
              uses: dorny/paths-filter@v2
              id: verify-changed-files
              with:
                  filters: |
                      db:
                        - 'services/bot/prisma/migrations/**'
                        - 'services/bot/prisma/schema.prisma'

            - name: Install Node v14
              if: steps.verify-changed-files.outputs.db == 'true'
              uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
              with:
                  node-version: "16"
                  cache: "yarn"

            - name: Run database migration if schema changed.
              if: steps.verify-changed-files.outputs.db == 'true'
              run: |
                  yarn global add prisma
                  cd services/bot
                  yarn migrate:prod:ci
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_MIGRATION_URL }}

            - name: Trigger deploy
              run: |
                  curl -X POST https://portainer.yoki-labs.xyz/api/stacks/webhooks/07d5969b-a1f8-4f15-875b-beb294c965c4
