name: Build Docker Containers
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "yoki/**"
            - "!yoki/site/**"
            - "docker/**"

jobs:
    docker:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [{ bot: "yoki", service: "bot" }, { bot: "yoki", service: "nsfw" }]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Verify Changed files
              uses: dorny/paths-filter@v2
              id: verify-changed-files
              with:
                  filters: |
                      service:
                        - '${{ matrix.service.bot }}/${{ matrix.service.service }}/**'
                        - 'docker/${{ matrix.service.bot }}/**'

            - name: Set up QEMU
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/setup-buildx-action@v2

            - name: Login to GCR
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}/${{ matrix.service.bot }}/${{ matrix.service.service }}:latest
                  file: docker/${{ matrix.service.bot }}/${{ matrix.service.service }}/Dockerfile
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
